### ISSUE TITLE
GATSBY: gatsby-transformer-sharp causing error in npm start

### ISSUE THREAD

**Issue by kldickenson** [mariohernandez/gatsby_training#5]
**ERROR reads:**
Error in "/Users/MyToy/Desktop/BADcamp-Gatsby/gatsby_training/gatsby/node_modules/gatsby-transformer-sharp/gatsby-node.js": 'linux-x64' binaries cannot be used on the 'darwin-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.

I did the suggested removal of 'node_modules/sharp/vendor', not helpful.

**My set up:**
macOS Catalina 10.15.7
nvm --version = 0.36.0
nvm ls
->     v10.14.2
       v11.15.0
       v12.18.4
       v13.11.0
         system
default -> stable (-> v13.11.0)
node -> stable (-> v13.11.0) (default)
stable -> 13.11 (-> v13.11.0) (default)
lando version v3.0.14 which uses:
Docker Desktop v2.3.0.5 & Docker Compose 1.27.2

'gatsby develop" did not work even though I have gatsby-cli globally installed, and also installed locally

**My solution that got "npm start" to work:**
gatsby.config.js = commented out 'gatsby-transformer-sharp' and 'gatsby-plugin-sharp'
package.json = removed both 'gatsby-transformer-sharp' and 'gatsby-plugin-sharp'

BUT then had an issue with the 'GatsbyImageSharpFluid', of course.
**Error message:**
There was an error in your GraphQL query:

The fragment "GatsbyImageSharpFluid" does not exist.

   1 | import { graphql } from 'gatsby';
>  2 | export const MovieFragment = graphql`
     |                                      ^^^^^^^^^^^^^^^^^^^^^^^^
   3 |   fragment MovieFragment on node__movie {
   4 |     id
   5 |     path {
   6 |       alias
   7 |     }
   8 |     title
   9 |     body {
  10 |       value
  11 |     }
  12 |     subtitle: field_promo_sentence

File: /Users/MyToy/Desktop/BADcamp-Gatsby/gatsby_training/gatsby/src/global/js/fragments.js

There was an error in your GraphQL query:

Cannot query field "childImageSharp" on type "File".

If you don't expect "childImageSharp" to exist on the type "File" it is most likely a typo.
However, if you expect "childImageSharp" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "childImageSharp" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "File":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/MyToy/Desktop/BADcamp-Gatsby/gatsby_training/gatsby/src/templates/movie.js

There was an error in your GraphQL query:

Unknown fragment "GatsbyImageSharpFluid".

GraphQL request:20:18
19 |             fluid(maxWidth: 1600, maxHeight: 900) {
20 |               ...GatsbyImageSharpFluid
   |                  ^
21 |             }

File: /Users/MyToy/Desktop/BADcamp-Gatsby/gatsby_training/gatsby/src/templates/movie.js

**Comment by kldickenson** [comment]
I pulled down your code today (I was 6 commits behind) and "gatsby develop" is working. 
Thank you,
Karen

**Comment by mariohernandez** [comment]
Thank you for the feedback, @kldickenson.  Glad it is working for you.

**Comment by mariohernandez** [comment]
Closing issue as this has been resolved with latest code updates.
